import { readdirSync, readFileSync, writeFileSync, statSync, existsSync } from "fs";
import { join, relative, dirname } from "path";

const SRC = join(__dirname, "..", "src");
const DOCS = join(__dirname, "..", "docs");
const OUT = join(DOCS, "ARCHITECTURE_MAP.md");

interface Node {
  path: string;
  type: "page" | "component" | "service" | "lib" | "type" | "hook";
  imports: string[];
}

function collectFiles(dir: string, base: string): Node[] {
  const nodes: Node[] = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) {
      if (!name.startsWith(".") && name !== "node_modules") {
        nodes.push(...collectFiles(p, base));
      }
    } else if (/\.(tsx?)$/.test(name)) {
      const rel = relative(base, p);
      const content = readFileSync(p, "utf-8");
      const imports: string[] = [];
      for (const line of content.split("\n")) {
        const m = line.match(/from\s+["'](@\/[^"']+)["']/);
        if (m) imports.push(m[1]);
      }
      let type: Node["type"] = "lib";
      if (rel.startsWith("app")) type = "page";
      else if (rel.startsWith("components")) type = "component";
      else if (rel.startsWith("services")) type = "service";
      else if (rel.startsWith("types")) type = "type";
      else if (rel.startsWith("hooks")) type = "hook";
      nodes.push({ path: rel, type, imports });
    }
  }
  return nodes;
}

function generate(): void {
  const nodes = collectFiles(SRC, SRC);
  const md: string[] = [];
  md.push("# Frontend Architecture Map\n");
  md.push("> Auto-generated by `scripts/generate-architecture-map.ts`\n");
  md.push("## Legend\n");
  md.push("- `page` — Next.js App Router page (route)\n");
  md.push("- `component` — Reusable UI component\n");
  md.push("- `service` — API service layer\n");
  md.push("- `lib` — Utility / library code\n");
  md.push("- `type` — TypeScript type definitions\n");
  md.push("- `hook` — React custom hook\n");
  md.push("\n## Route-to-Service Dependency Graph\n");
  md.push("| Route / Module | Type | Depends On |\n");
  md.push("|---|---|---|\n");
  const routes = nodes.filter((n) => n.type === "page");
  for (const r of routes) {
    const deps = r.imports.filter((i) => i.startsWith("@/services/")).map((i) => i.replace("@/", "`src/") + "`").join(", ") || "—";
    const libDeps = r.imports.filter((i) => i.startsWith("@/lib/")).map((i) => i.replace("@/", "`src/") + "`").join(", ") || "—";
    md.push(`| \`src/${r.path}\` | page | Services: ${deps}<br/>Libs: ${libDeps} |\n`);
  }
  md.push("\n## All Modules\n");
  md.push("| Module | Type | Imports |\n");
  md.push("|---|---|---|\n");
  for (const n of nodes) {
    const deps = n.imports.length ? n.imports.join(", ") : "—";
    md.push(`| \`src/${n.path}\` | ${n.type} | ${deps} |\n`);
  }
  if (!existsSync(DOCS)) {
    return;
  }
  writeFileSync(OUT, md.join(""), "utf-8");
  console.log(`Architecture map written to ${OUT}`);
}

generate();
